export DatabaseStorageAdapterIntegrationTest from "./DatabaseStorageAdapterIntegrationTestSuite";
export DatabaseStorageAdapterTestSuite from "./DatabaseStorageAdapterTestSuite";
export FileSystemStorageAdapterTestSuite from "./FileSystemStorageAdapterTestSuite";